port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
- name: skskksk-tro-sgdo003.tunggure.buzz
  server: investor.fb.com
  port: 443
  type: trojan
  password: skskksk
  skip-cert-verify: true
  sni: tro-sgdo003.tunggure.buzz
  network: ws
  ws-opts:
    path: /trojan-go
    headers:
      Host: tro-sgdo003.tunggure.buzz
  udp: true
proxy-groups:
  - name: SAHABATSSH
    type: select
    proxies:
      - skskksk-tro-sgdo003.tunggure.buzz
      - DIRECT
rules:
  - MATCH,SAHABATSSH
